### ISSUE TITLE
Suggest requirement.txt in this repository

### ISSUE THREAD

**Issue by Taeyoung96** [gisbi-kim/modern-slam-tutorial-python#1]
안녕하세요. 좋은 tutorial 영상 및 코드 감사드립니다.  
제안 사항이 있는데요.  

Anaconda를 활용하여 환경을 구성하셨는데, requirement.txt를 같이 repository에 첨부하면 좋을 것 같습니다.  

저도 Anaconda를 활용해서 Tutorial 영상을 따라해보았는데요.  

실례가 되지 않는다면, 혹시 requirement.txt를 올리지 않을 예정이시면,  
제가 사용했던 가상환경 requirement.txt 파일을 PR로 보내도 될까요?  

저는 Ubuntu 18.04에서 실험을 진행해보았습니다.   
가상환경을 구성할 때,  
- python version : 3.7  
- pip install gtsam  
- pip install jupyterlab  
- pip install pytictoc  
- conda install jupyter   

을 활용했습니다!  

감사합니다.  :smile:

**Comment by gisbi-kim** [comment]
네 PR주시면 받을게요 
사용해주셔서 + 기여해주셔서 감사합니다!

**Comment by ZeyingXuHuaWei** [comment]
hello,  could you tell me what gtsam version are you using?  I use gtsam4.0.2 and the following lines have errors
        node_idx_from = factor.keys()[0]           //    it worked with  node_idx_from = factor.keys().front()
        node_idx_to = factor.keys()[1]               //    it worked with  node_idx_from = factor.keys().back()
        measurement = factor.measured()       //     error NonLinearFactor do not have measured,      how to fix this ???????

**Comment by Taeyoung96** [comment]
@ZeyingXuHuaWei 
In my case, I used gtsam 4.1.0.
